# Generated by Django 3.0.7 on 2020-10-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
        ('users', '0003_auto_20201030_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repo.Department'),
            preserve_default=False,
        ),
    ]
