# Generated by Django 3.2 on 2021-04-18 08:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Dep_admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Equipment_No', models.CharField(max_length=100, unique=True)),
                ('Code', models.CharField(max_length=100, unique=True)),
                ('Status', models.CharField(max_length=100)),
                ('Other_Info', models.TextField()),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.department')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_No', models.CharField(max_length=100, unique=True)),
                ('Supplier_Info', models.TextField()),
                ('Date_YYYYMMDD', models.DateField(default=datetime.date.today)),
                ('Rate_With_VAT', models.FloatField()),
                ('Total_Cost_With_VAT', models.FloatField()),
                ('GI_No', models.IntegerField(unique=True)),
                ('Remark', models.CharField(default='ok', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_no', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=100)),
                ('Area_In_sq_m', models.IntegerField(default=0)),
                ('Seating_Capacity', models.IntegerField(default=0)),
                ('Total_cost', models.FloatField(default=0)),
                ('Other_Data', models.TextField(blank=True, null=True)),
                ('No_of_Fans', models.IntegerField(default=0)),
                ('No_of_AC', models.IntegerField(default=0)),
                ('No_of_Light_Sounce', models.IntegerField(default=0)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.department')),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repo.room')),
                ('Details', models.TextField(blank=True, null=True)),
                ('No_of_Tables', models.IntegerField(default=0)),
                ('Intercom_No', models.IntegerField(blank=True, default=0, null=True)),
            ],
            bases=('repo.room',),
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repo.room')),
                ('Teaching_Tools', models.TextField()),
                ('is_stepped_Room', models.BooleanField(default=False)),
                ('No_of_benches', models.IntegerField(default=0)),
            ],
            bases=('repo.room',),
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repo.item')),
            ],
            bases=('repo.item',),
        ),
        migrations.CreateModel(
            name='UserDepartmentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Sub_Admin', models.BooleanField(default=False)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.department')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Licenced_Qty', models.IntegerField(blank=True, null=True)),
                ('Software_No', models.IntegerField(unique=True)),
                ('Code', models.CharField(max_length=100, unique=True)),
                ('GI_No', models.IntegerField(unique=True)),
                ('Status', models.CharField(default='Ok', max_length=100)),
                ('Invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='Invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.purchase'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=100)),
                ('Info', models.TextField()),
                ('Date_YYYYMMDD', models.DateField(auto_now_add=True)),
                ('Is_Solved', models.BooleanField(default=False)),
                ('Creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repo.room')),
                ('Extension_No', models.IntegerField(blank=True, default=0, null=True)),
                ('Intercom_No', models.IntegerField(blank=True, default=0, null=True)),
                ('Practicals_conducted_Odd_SEM', models.CharField(default='None', max_length=300)),
                ('Practicals_conducted_Even_SEM', models.CharField(default='None', max_length=300)),
                ('Lab_Assistant_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_assistant_1', to=settings.AUTH_USER_MODEL)),
                ('Lab_Assistant_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_assistant_2', to=settings.AUTH_USER_MODEL)),
                ('Lab_Incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_incharge', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('repo.room',),
        ),
        migrations.AddField(
            model_name='item',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.laboratory'),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='repo.item')),
                ('RAM', models.IntegerField()),
                ('Storage_in_GB', models.IntegerField()),
                ('Processor', models.CharField(max_length=100)),
                ('Installed_Softwares', models.ManyToManyField(blank=True, to='repo.Software')),
            ],
            bases=('repo.item',),
        ),
    ]
