# Generated by Django 3.2 on 2021-04-10 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, unique=True)),
                ('Dep_admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_No', models.CharField(max_length=20, unique=True)),
                ('Supplier_Info', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Rate_With_VAT', models.FloatField()),
                ('Total_Cost_With_VAT', models.FloatField()),
                ('GI_No', models.IntegerField(unique=True)),
                ('Remark', models.CharField(default='ok', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserDepartmentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Sub_Admin', models.BooleanField(default=False)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.department')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Licenced_Qty', models.IntegerField(blank=True, null=True)),
                ('software_no', models.IntegerField(unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('gi_no', models.IntegerField(unique=True)),
                ('Status', models.CharField(default='Ok', max_length=60)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lab_Number', models.IntegerField(default=0, unique=True)),
                ('Name', models.CharField(max_length=20, unique=True)),
                ('Lab_Area_In_sqft', models.IntegerField(default=0)),
                ('Lab_Capacity', models.IntegerField(default=0)),
                ('Intercom_No', models.IntegerField(blank=True, default=0, null=True, unique=True)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.department')),
                ('Lab_Incharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=40)),
                ('Info', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Is_Solved', models.BooleanField(default=False)),
                ('Creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Equipment_No', models.CharField(max_length=10, unique=True)),
                ('Code', models.CharField(max_length=10, unique=True)),
                ('Status', models.CharField(max_length=60)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.department')),
                ('Invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.purchase')),
                ('Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Equipment_No', models.CharField(max_length=10, unique=True)),
                ('Code', models.CharField(max_length=100, unique=True)),
                ('Status', models.CharField(max_length=60)),
                ('RAM', models.IntegerField()),
                ('Storage_in_GB', models.IntegerField()),
                ('Other_Info', models.TextField(max_length=200)),
                ('Department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.department')),
                ('Installed_Softwares', models.ManyToManyField(blank=True, null=True, to='repo.Software')),
                ('Invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.purchase')),
                ('Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.lab')),
            ],
        ),
    ]
