# Generated by Django 3.2 on 2021-04-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='gi_no',
            new_name='GI_No',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='purchase',
            new_name='Invoice',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='software_no',
            new_name='Software_No',
        ),
    ]
