# Generated by Django 3.0.7 on 2020-07-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='Qty',
        ),
    ]
