# Generated by Django 3.2 on 2021-04-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='Installed_Softwares',
            field=models.ManyToManyField(blank=True, to='repo.Software'),
        ),
    ]
