# Generated by Django 3.0.7 on 2020-10-30 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perchase',
            new_name='Purchase',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='perchase',
            new_name='purchase',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='perchase',
            new_name='purchase',
        ),
        migrations.RenameField(
            model_name='software',
            old_name='perchase',
            new_name='purchase',
        ),
    ]
