# Generated by Django 3.2 on 2021-04-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_alter_item_other_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Room_no',
            field=models.CharField(max_length=10),
        ),
    ]
