# Generated by Django 3.2 on 2021-04-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_alter_computer_installed_softwares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='Processor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='Header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='Code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Equipment_No',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Invoice_No',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Remark',
            field=models.CharField(default='ok', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='software',
            name='Code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='Status',
            field=models.CharField(default='Ok', max_length=100),
        ),
    ]
