# Generated by Django 3.0.7 on 2020-07-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_remove_equipment_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'permissions': [('sub_admin', 'view,edit,delete,add'), ('teacher', 'view')]},
        ),
    ]
