# Generated by Django 3.1.3 on 2020-11-06 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0003_auto_20201106_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepartmentmapping',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdepartmentmapping',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
