# Generated by Django 3.2 on 2021-04-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_auto_20210418_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Area_In_sqft',
            new_name='Area_In_sq_m',
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_no',
            field=models.IntegerField(default=0),
        ),
    ]
