# Generated by Django 3.0.7 on 2020-07-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_auto_20200724_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'permissions': [('sub_admin', 'sub_admin'), ('teacher', 'teacher')]},
        ),
    ]
