# Generated by Django 3.2 on 2021-04-18 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_alter_room_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Date_YYYYMMDD',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
