# Generated by Django 3.0.7 on 2020-11-04 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20201104_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDepMapping',
        ),
    ]
