# Generated by Django 3.2 on 2021-04-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20210418_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='Intercom_No',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='Intercom_No',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
