# Generated by Django 3.0.7 on 2020-07-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20200724_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labequipmentmapping',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipnments', to='repo.Lab'),
        ),
    ]
