# Generated by Django 3.2 on 2021-04-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_alter_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='Other_Data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='Practicals_conducted_Even_SEM',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='Practicals_conducted_Odd_SEM',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='Seating_Capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lab',
            name='Total_Lab_cost',
            field=models.FloatField(default=0),
        ),
    ]
