# Generated by Django 3.1.3 on 2020-11-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='installed_software',
            field=models.ManyToManyField(blank=True, null=True, to='repo.Software'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='intercom_no',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bill_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_no',
            field=models.IntegerField(unique=True),
        ),
    ]
