# Generated by Django 3.0.7 on 2020-07-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20200725_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'permissions': [('sub_admin', 'sub_admin'), ('teacher', 'teacher'), ('viewr', 'view')]},
        ),
    ]
