# Generated by Django 3.2 on 2021-04-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20210418_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='',
            new_name='Date_YYYYMMDD',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='',
            new_name='Date_YYYYMMDD',
        ),
    ]
