# Generated by Django 3.2 on 2021-04-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20210412_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='Practicals_conducted_Even_SEM',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='lab',
            name='Practicals_conducted_Odd_SEM',
            field=models.CharField(max_length=300),
        ),
    ]
