# Generated by Django 3.0.7 on 2020-11-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_delete_userdepmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='Licenced_Qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
