# Generated by Django 3.2 on 2021-06-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_auto_20210502_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Total_cost',
        ),
    ]
