# Generated by Django 3.1.3 on 2020-11-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_auto_20201107_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='purchase',
            new_name='purchase_bill_no',
        ),
        migrations.RenameField(
            model_name='lab',
            old_name='lab_area',
            new_name='lab_area_in_sqft',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='invoice',
            new_name='invoice_no',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='rate',
            new_name='rate_in_Rupee',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='supplier',
            new_name='supplier_info',
        ),
    ]
