# Generated by Django 3.2 on 2021-04-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_auto_20210412_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='Lab_Capacity',
        ),
        migrations.AddField(
            model_name='lab',
            name='Extension_No',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
