# Generated by Django 3.0.7 on 2020-07-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0006_auto_20200725_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'permissions': [('sub_admin', 'sub_admin'), ('teacher', 'teacher')]},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'permissions': [('sub_admin', 'sub_admin'), ('teacher', 'teacher')]},
        ),
    ]
