# Generated by Django 3.0.7 on 2020-11-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0007_userdepartmentmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdepartmentmapping',
            old_name='user',
            new_name='id',
        ),
    ]
