# Generated by Django 3.0.7 on 2020-07-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0007_auto_20200725_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'permissions': [('sub_admin', 'sub admin'), ('teacher', 'teacher')]},
        ),
    ]
