# Generated by Django 3.1.3 on 2020-11-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0007_auto_20201107_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepartmentmapping',
            name='is_sub_admin',
            field=models.BooleanField(default=False),
        ),
    ]
