# Generated by Django 3.2 on 2021-07-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0007_remove_room_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Invoice_No',
            new_name='Invoice',
        ),
    ]
