# Generated by Django 3.2 on 2021-04-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0007_auto_20210416_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='Name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Equipment_No',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Invoice_No',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='Name',
            field=models.TextField(),
        ),
    ]
