# Generated by Django 3.2 on 2021-04-17 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repo', '0008_auto_20210416_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='Lab_Assistant_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_assistant_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lab',
            name='Lab_Assistant_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_assistant_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='computer',
            name='Installed_Softwares',
            field=models.ManyToManyField(to='repo.Software'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='Lab_Incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_incharge', to=settings.AUTH_USER_MODEL),
        ),
    ]
