# Generated by Django 3.1.3 on 2020-11-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0008_userdepartmentmapping_is_sub_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='department',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='software',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='userdepartmentmapping',
            name='deleted',
        ),
    ]
