# Generated by Django 3.0.7 on 2020-07-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0009_auto_20200725_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={},
        ),
    ]
