# Generated by Django 3.2 on 2021-04-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0009_auto_20210417_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='Practicals_conducted_Even_SEM',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='lab',
            name='Practicals_conducted_Odd_SEM',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
