# Generated by Django 3.0.7 on 2020-07-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0010_auto_20200725_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'permissions': [('sub_admin', 'sub_admin_status'), ('teacher', 'teacher')]},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'permissions': [('sub_admin', 'sub_admin_status'), ('teacher', 'teacher')]},
        ),
    ]
