# Generated by Django 3.0.7 on 2020-07-26 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0011_auto_20200725_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='lab',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='equipnments', to='repo.Lab'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='labEquipmentMapping',
        ),
    ]
