# Generated by Django 3.0.7 on 2020-07-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0013_auto_20200726_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='supplier',
            new_name='supplier_or_site',
        ),
        migrations.RemoveField(
            model_name='software',
            name='Qty',
        ),
        migrations.AddField(
            model_name='software',
            name='Licenced_Qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='Status',
            field=models.CharField(default='Ok', max_length=60),
        ),
        migrations.CreateModel(
            name='ComputerSoftwareMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.Equipment')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.Software')),
            ],
        ),
    ]
