# Generated by Django 3.0.7 on 2020-08-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0014_auto_20200726_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersoftwaremapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='labfacultymapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='software',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
