# Generated by Django 3.0.7 on 2020-08-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0015_auto_20200805_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computersoftwaremapping',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='labfacultymapping',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='software',
            name='is_active',
        ),
    ]
