# Generated by Django 3.0.7 on 2020-08-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0016_auto_20200805_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersoftwaremapping',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='labfacultymapping',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='software',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='computersoftwaremapping',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.Equipment'),
        ),
        migrations.AlterField(
            model_name='computersoftwaremapping',
            name='software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.Software'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.Department'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.Department'),
        ),
        migrations.AlterField(
            model_name='labfacultymapping',
            name='faculty_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_department', to='repo.Department'),
        ),
        migrations.AlterField(
            model_name='labfacultymapping',
            name='lab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.Lab'),
        ),
        migrations.AlterField(
            model_name='labfacultymapping',
            name='subject_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_department', to='repo.Department'),
        ),
        migrations.AlterField(
            model_name='software',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='repo.Department'),
        ),
    ]
